// Hand-built stand-in until fixtures/*.json land. Synthetic patient, placeholder trial ID.
// Shapes match src/contracts exactly; source.ts validates them with zod on load.
// Cell verdicts are criterion-oriented (CONTRACT §4 ruling): an exclusion the patient
// clears is FAIL, a matched exclusion is PASS and eliminates the trial.

export const AS_OF = "2026-09-25";

export const placeholderTrials = [
  {
    nctId: "NCT09900001",
    title:
      "Fourth-generation EGFR inhibitor vs platinum doublet after progression on first-line EGFR TKI",
    phase: "PHASE3",
    condition: "EGFR-mutant non-small cell lung cancer",
    slots: 4,
    siteDistanceMinutes: 38,
    compilerConfidence: 0.93,
    needsHumanReview: false,
    criteria: [
      {
        kind: "leaf",
        id: "INC-1",
        type: "inclusion",
        predicate: "age",
        operator: ">=",
        value: 18,
        tier: 1,
        sweepable: true,
        sweepRange: [18, 80],
        sweepStep: 1,
        sourceSpan: "Age ≥ 18 years at the time of signing informed consent.",
      },
      {
        kind: "leaf",
        id: "INC-2",
        type: "inclusion",
        predicate: "staging",
        operator: "in",
        value: ["IIIB", "IIIC", "IV"],
        tier: 2,
        sweepable: false,
        sourceSpan:
          "Histologically confirmed locally advanced (stage IIIB/IIIC) or metastatic (stage IV) NSCLC not amenable to curative therapy.",
      },
      {
        kind: "leaf",
        id: "INC-3",
        type: "inclusion",
        predicate: "biomarker",
        operator: "in",
        value: ["L858R", "ex19del"],
        analyte: "EGFR",
        tier: 0,
        sweepable: false,
        sourceSpan:
          "Documented EGFR exon 19 deletion or exon 21 L858R mutation by a validated tissue or plasma assay.",
      },
      {
        kind: "leaf",
        id: "INC-4",
        type: "inclusion",
        predicate: "biomarker",
        operator: "==",
        value: "negative",
        analyte: "EGFR T790M",
        tier: 0,
        pFavorable: 0.45,
        sweepable: false,
        sourceSpan:
          "Absence of EGFR T790M on a tissue sample obtained after progression on the most recent EGFR TKI.",
      },
      {
        kind: "leaf",
        id: "INC-5",
        type: "inclusion",
        predicate: "performance_status",
        operator: "<=",
        value: 1,
        maxAgeDays: 28,
        tier: 1,
        sweepable: true,
        sweepRange: [0, 2],
        sweepStep: 1,
        sourceSpan: "ECOG performance status of 0 or 1.",
      },
      {
        kind: "group",
        op: "AND",
        sourceSpan: "Adequate organ function within 14 days before randomisation, defined as:",
        children: [
          {
            kind: "leaf",
            id: "INC-6a",
            type: "inclusion",
            predicate: "lab_value",
            operator: ">=",
            value: 1500,
            unit: "/uL",
            analyte: "ANC",
            maxAgeDays: 14,
            tier: 1,
            sweepable: true,
            sweepRange: [1000, 2000],
            sweepStep: 100,
            sourceSpan: "Absolute neutrophil count ≥ 1.5 × 10⁹/L",
          },
          {
            kind: "leaf",
            id: "INC-6b",
            type: "inclusion",
            predicate: "lab_value",
            operator: ">=",
            value: 100000,
            unit: "/uL",
            analyte: "platelets",
            maxAgeDays: 14,
            tier: 1,
            sweepable: true,
            sweepRange: [50000, 150000],
            sweepStep: 10000,
            sourceSpan: "Platelets ≥ 100 × 10⁹/L",
          },
          {
            kind: "leaf",
            id: "INC-6c",
            type: "inclusion",
            predicate: "lab_value",
            operator: ">=",
            value: 50,
            unit: "mL/min",
            analyte: "creatinine clearance",
            maxAgeDays: 14,
            tier: 1,
            pFavorable: 0.85,
            sweepable: true,
            sweepRange: [30, 60],
            sweepStep: 5,
            sourceSpan: "Creatinine clearance ≥ 50 mL/min (Cockcroft–Gault)",
          },
        ],
      },
      {
        kind: "group",
        op: "OR",
        sourceSpan: "At least one of the following:",
        children: [
          {
            kind: "leaf",
            id: "INC-7a",
            type: "inclusion",
            predicate: "staging",
            operator: "==",
            value: "measurable",
            maxAgeDays: 28,
            tier: 2,
            sweepable: false,
            sourceSpan: "At least one measurable lesion per RECIST v1.1",
          },
          {
            kind: "leaf",
            id: "INC-7b",
            type: "inclusion",
            predicate: "staging",
            operator: "==",
            value: "evaluable_bone",
            maxAgeDays: 28,
            tier: 2,
            sweepable: false,
            sourceSpan: "Evaluable bone-only disease on bone scan or PET-CT",
          },
        ],
      },
      {
        kind: "leaf",
        id: "EXC-1",
        type: "exclusion",
        predicate: "prior_therapy",
        operator: "in",
        value: ["osimertinib", "lazertinib", "aumolertinib"],
        drugClass: "EGFR_TKI_3G",
        members: ["osimertinib", "lazertinib", "aumolertinib"],
        tier: 1,
        sweepable: false,
        sourceSpan: "Prior treatment with any third-generation EGFR TKI.",
      },
      {
        kind: "leaf",
        id: "EXC-2",
        type: "exclusion",
        predicate: "comorbidity",
        operator: "==",
        value: "interstitial lung disease",
        tier: 1,
        sweepable: false,
        sourceSpan:
          "History of interstitial lung disease, drug-induced ILD, or radiation pneumonitis requiring steroids.",
      },
      {
        kind: "leaf",
        id: "EXC-3",
        type: "exclusion",
        predicate: "lab_value",
        operator: ">",
        value: 470,
        unit: "ms",
        analyte: "QTc",
        maxAgeDays: 28,
        tier: 1,
        sweepable: true,
        sweepRange: [450, 500],
        sweepStep: 5,
        sourceSpan: "Mean resting corrected QT interval (QTcF) > 470 ms on screening ECG.",
      },
      {
        kind: "leaf",
        id: "EXC-4",
        type: "exclusion",
        predicate: "washout",
        operator: "<",
        value: 8,
        unit: "days",
        drugClass: "EGFR_TKI",
        tier: 4,
        sweepable: true,
        sweepRange: [0, 21],
        sweepStep: 1,
        sourceSpan: "Treatment with an EGFR TKI within 8 days before the first dose of study drug.",
      },
    ],
  },
];

export const placeholderPatients = [
  {
    id: "PT-4417",
    age: 64,
    sex: "F",
    race: "Asian",
    ethnicity: "Not Hispanic or Latino",
    zip: "02139",
    travelMinutes: 38,
    facts: [],
  },
];

const cellBase = { patientId: "PT-4417", nctId: "NCT09900001" } as const;

export const placeholderCube = [
  {
    patientId: "PT-4417",
    nctId: "NCT09900001",
    eliminated: false,
    passCount: 7,
    failCount: 5,
    unknownCount: 2,
    resolutionCost: 3,
    expectedValue: 0.43,
    cells: [
      {
        ...cellBase,
        criterionId: "INC-1",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation: "Age ≥ 18 years at the time of signing informed consent.",
        chartCitation: "64-year-old woman, never-smoker, referred for second-line options.",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "INC-2",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation:
          "Histologically confirmed locally advanced (stage IIIB/IIIC) or metastatic (stage IV) NSCLC not amenable to curative therapy.",
        chartCitation:
          "Adenocarcinoma of the right upper lobe, stage IVA (cT2a N2 M1a) with malignant pleural effusion.",
        tier: 2,
        observedAt: "2025-11-04",
        ageDays: 325,
      },
      {
        ...cellBase,
        criterionId: "INC-3",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation:
          "Documented EGFR exon 19 deletion or exon 21 L858R mutation by a validated tissue or plasma assay.",
        chartCitation: "NGS on the diagnostic core biopsy identified EGFR exon 21 L858R (VAF 31%).",
        tier: 0,
        observedAt: "2025-11-12",
        ageDays: 317,
      },
      {
        ...cellBase,
        criterionId: "INC-4",
        verdict: "UNKNOWN",
        reason: "absent",
        criterionCitation:
          "Absence of EGFR T790M on a tissue sample obtained after progression on the most recent EGFR TKI.",
        tier: 0,
        pFavorable: 0.45,
      },
      {
        ...cellBase,
        criterionId: "INC-5",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation: "ECOG performance status of 0 or 1.",
        chartCitation: "ECOG 1 — ambulatory, able to carry out light work.",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "INC-6a",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation: "Absolute neutrophil count ≥ 1.5 × 10⁹/L",
        chartCitation: "ANC 3,200 /uL",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "INC-6b",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation: "Platelets ≥ 100 × 10⁹/L",
        chartCitation: "Platelets 214,000 /uL",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "INC-6c",
        verdict: "UNKNOWN",
        reason: "stale",
        criterionCitation: "Creatinine clearance ≥ 50 mL/min (Cockcroft–Gault)",
        chartCitation: "Serum creatinine 0.8 mg/dL; estimated CrCl 71 mL/min.",
        tier: 1,
        pFavorable: 0.85,
        observedAt: "2026-03-12",
        ageDays: 197,
      },
      {
        ...cellBase,
        criterionId: "INC-7a",
        verdict: "PASS",
        reason: "satisfied",
        criterionCitation: "At least one measurable lesion per RECIST v1.1",
        chartCitation:
          "Restaging CT: enlarging right upper lobe mass, 3.4 cm (previously 2.1 cm); new 1.2 cm left adrenal nodule.",
        tier: 2,
        observedAt: "2026-09-10",
        ageDays: 15,
      },
      {
        ...cellBase,
        criterionId: "INC-7b",
        verdict: "FAIL",
        reason: "contradicted",
        criterionCitation: "Evaluable bone-only disease on bone scan or PET-CT",
        chartCitation: "No osseous lesions identified.",
        tier: 2,
        observedAt: "2026-09-10",
        ageDays: 15,
      },
      {
        ...cellBase,
        criterionId: "EXC-1",
        verdict: "FAIL",
        reason: "contradicted",
        criterionCitation: "Prior treatment with any third-generation EGFR TKI.",
        chartCitation:
          "Treatment history: erlotinib 150 mg daily from 2025-11-20; progression on restaging CT 2026-09-10. No other systemic therapy.",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "EXC-2",
        verdict: "FAIL",
        reason: "contradicted",
        criterionCitation:
          "History of interstitial lung disease, drug-induced ILD, or radiation pneumonitis requiring steroids.",
        chartCitation: "No history of interstitial lung disease or pneumonitis.",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "EXC-3",
        verdict: "FAIL",
        reason: "contradicted",
        criterionCitation: "Mean resting corrected QT interval (QTcF) > 470 ms on screening ECG.",
        chartCitation: "ECG: sinus rhythm, QTcF 432 ms.",
        tier: 1,
        observedAt: "2026-09-18",
        ageDays: 7,
      },
      {
        ...cellBase,
        criterionId: "EXC-4",
        verdict: "FAIL",
        reason: "contradicted",
        criterionCitation:
          "Treatment with an EGFR TKI within 8 days before the first dose of study drug.",
        chartCitation: "Erlotinib discontinued 2026-09-12 at progression.",
        tier: 4,
        observedAt: "2026-09-12",
        ageDays: 13,
      },
    ],
  },
];
