import type { Patient } from "@/src/contracts";

/**
 * Hand-written DE-SynPUF-shaped records. Swap for data/claims/patients.json
 * when the compiler lane lands the real extract. Every quote is a claim line,
 * never a chart sentence. Labelled synthetic — contract §9.
 */
export const CLAIMS_STUB: Patient[] = [
  {
    id: "BENE-441201",
    age: 74,
    sex: "F",
    race: "White",
    ethnicity: "Not Hispanic or Latino",
    zip: "02115",
    travelMinutes: 18,
    facts: [
      {
        predicate: "age",
        value: 74,
        unit: "years",
        observedAt: "2009-01-01",
        sourceQuote: "Beneficiary summary: birth year 1935 → age 74 at as-of.",
        sourceDoc: "CMS DE-SynPUF beneficiary summary 2009",
        provenance: "claims",
      },
      {
        predicate: "diagnosis",
        value: "non-small cell lung cancer",
        observedAt: "2009-06-11",
        sourceQuote: "Inpatient claim ICD-9 162.3 (upper lobe bronchus/lung), DOS 2009-06-11, DRG 082.",
        sourceDoc: "CMS DE-SynPUF inpatient 2009",
        provenance: "claims",
      },
      {
        predicate: "prior_therapy",
        analyte: "osimertinib",
        drugClass: "EGFR_TKI",
        value: true,
        observedAt: "2009-08-03",
        sourceQuote: "Part D PDE NDC 00310-0269-30 osimertinib 80 mg × 30, DOS 2009-08-03, $14,208.",
        sourceDoc: "CMS DE-SynPUF PDE 2009",
        provenance: "claims",
      },
    ],
  },
  {
    id: "BENE-441202",
    age: 69,
    sex: "M",
    race: "Black or African American",
    ethnicity: "Not Hispanic or Latino",
    zip: "30303",
    travelMinutes: 32,
    facts: [
      {
        predicate: "age",
        value: 69,
        unit: "years",
        observedAt: "2010-01-01",
        sourceQuote: "Beneficiary summary: birth year 1941 → age 69 at as-of.",
        sourceDoc: "CMS DE-SynPUF beneficiary summary 2010",
        provenance: "claims",
      },
      {
        predicate: "diagnosis",
        value: "non-small cell lung cancer",
        observedAt: "2010-02-18",
        sourceQuote: "Carrier claim ICD-9 162.9 (bronchus/lung unspecified), DOS 2010-02-18.",
        sourceDoc: "CMS DE-SynPUF carrier 2010",
        provenance: "claims",
      },
      {
        predicate: "comorbidity",
        analyte: "ILD",
        value: true,
        observedAt: "2010-04-18",
        sourceQuote: "Carrier claim ICD-9 516.3 idiopathic fibrosing alveolitis, DOS 2010-04-18, BETOS T2D.",
        sourceDoc: "CMS DE-SynPUF carrier 2010",
        provenance: "claims",
      },
    ],
  },
  {
    id: "BENE-441203",
    age: 71,
    sex: "F",
    race: "Asian",
    ethnicity: "Not Hispanic or Latino",
    zip: "94110",
    travelMinutes: 24,
    facts: [
      {
        predicate: "age",
        value: 71,
        unit: "years",
        observedAt: "2008-01-01",
        sourceQuote: "Beneficiary summary: birth year 1937 → age 71 at as-of.",
        sourceDoc: "CMS DE-SynPUF beneficiary summary 2008",
        provenance: "claims",
      },
      {
        predicate: "diagnosis",
        value: "non-small cell lung cancer",
        observedAt: "2008-09-22",
        sourceQuote: "Outpatient claim ICD-9 162.5 (lower lobe bronchus/lung), DOS 2008-09-22.",
        sourceDoc: "CMS DE-SynPUF outpatient 2008",
        provenance: "claims",
      },
      {
        predicate: "lab_value",
        analyte: "ANC",
        value: 2400,
        unit: "/uL",
        observedAt: "2008-10-02",
        sourceQuote: "Carrier claim HCPCS 85025 CBC with differential, DOS 2008-10-02 — billed, result not on the claim.",
        sourceDoc: "CMS DE-SynPUF carrier 2008",
        provenance: "claims",
      },
      {
        predicate: "biomarker",
        analyte: "EGFR",
        value: "L858R",
        observedAt: "2008-10-14",
        sourceQuote: "Carrier claim HCPCS 81235 EGFR gene analysis, DOS 2008-10-14 — billed, variant not on the claim.",
        sourceDoc: "CMS DE-SynPUF carrier 2008",
        provenance: "claims",
      },
    ],
  },
  {
    id: "BENE-441204",
    age: 66,
    sex: "M",
    race: "White",
    ethnicity: "Not Hispanic or Latino",
    zip: "75201",
    travelMinutes: 41,
    facts: [
      {
        predicate: "age",
        value: 66,
        unit: "years",
        observedAt: "2010-01-01",
        sourceQuote: "Beneficiary summary: birth year 1944 → age 66 at as-of.",
        sourceDoc: "CMS DE-SynPUF beneficiary summary 2010",
        provenance: "claims",
      },
    ],
  },
];
